# Generated by Django 4.2.27 on 2025-12-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='VisitBooking',
        ),
        migrations.AlterModelTable(
            name='visitbooking',
            table='visit_bookings',
        ),
    ]
